#!/usr/bin/env bash
set -euo pipefail

# Cloudflare IP CIDR Auto-Sync Script
# Generates Nginx, Caddy, and Go CIDR configuration fragments.
# Usage: sudo bash deploy/scripts/update-cloudflare-ip.sh

NGINX_OUT="/etc/nginx/conf.d/cloudflare-realip.conf"
CADDY_OUT="/etc/caddy/cloudflare-trusted.conf"
GO_OUT="/etc/ip-lookup/cf-cidrs.txt"
TEMP_DIR=$(mktemp -d)
TEMP_NGINX="${TEMP_DIR}/cloudflare-realip.conf"
TEMP_CADDY="${TEMP_DIR}/cloudflare-trusted.conf"
TEMP_GO="${TEMP_DIR}/cf-cidrs.txt"

cleanup() {
	rm -rf "${TEMP_DIR}"
}
trap cleanup EXIT

log_info() {
	echo "[INFO] $(date '+%Y-%m-%d %H:%M:%S') $*"
}

log_error() {
	echo "[ERROR] $(date '+%Y-%m-%d %H:%M:%S') $*" >&2
}

fetch_cidr() {
	local url="$1"
	local label="$2"
	local data
	local max_retries=3
	local delay=5

	for attempt in $(seq 1 "${max_retries}"); do
		data=$(curl -sS --fail --max-time 30 "$url" 2>/dev/null) && break
		log_error "Failed to fetch ${label} from ${url} (attempt ${attempt}/${max_retries})"
		if [ "${attempt}" -lt "${max_retries}" ]; then
			sleep "${delay}"
			delay=$((delay * 2))
		else
			return 1
		fi
	done

	if [ -z "$data" ]; then
		log_error "Empty response for ${label}"
		if [ "${max_retries}" -gt 1 ]; then
			return 1
		fi
	fi

	echo "$data"
}

log_info "Fetching Cloudflare IPv4 CIDRs..."
IPV4=$(fetch_cidr "https://www.cloudflare.com/ips-v4" "IPv4") || exit 1

log_info "Fetching Cloudflare IPv6 CIDRs..."
IPV6=$(fetch_cidr "https://www.cloudflare.com/ips-v6" "IPv6") || exit 1

ALL_CIDRS=$(printf "%s\n%s\n" "$IPV4" "$IPV6" | grep -v '^$' | sort -u)

if [ -z "$ALL_CIDRS" ]; then
	log_error "No CIDRs fetched, aborting"
	exit 1
fi

log_info "Generating Nginx config: ${TEMP_NGINX}"
cat > "${TEMP_NGINX}" <<'NGINX_HEAD'
# Cloudflare Real IP Configuration
# Auto-generated by update-cloudflare-ip.sh
# Last updated: {{DATE}}
# Source: https://www.cloudflare.com/ips-v4 / ips-v6

NGINX_HEAD
sed -i "s/{{DATE}}/$(date -u '+%Y-%m-%d %H:%M:%S UTC')/" "${TEMP_NGINX}"

echo "$ALL_CIDRS" | while read -r cidr; do
	echo "set_real_ip_from ${cidr};" >> "${TEMP_NGINX}"
done
cat >> "${TEMP_NGINX}" <<'NGINX_TAIL'
real_ip_header CF-Connecting-IP;
real_ip_recursive on;
NGINX_TAIL

log_info "Generating Caddy config: ${TEMP_CADDY}"
cat > "${TEMP_CADDY}" <<'CADDY_HEAD'
# Cloudflare Trusted Proxies for Caddy
# Auto-generated by update-cloudflare-ip.sh
# Last updated: {{DATE}}
# Import with: trusted_proxies static { import /etc/caddy/cloudflare-trusted.conf }

CADDY_HEAD
sed -i "s/{{DATE}}/$(date -u '+%Y-%m-%d %H:%M:%S UTC')/" "${TEMP_CADDY}"

echo "$ALL_CIDRS" | while read -r cidr; do
	echo "${cidr}" >> "${TEMP_CADDY}"
done

log_info "Generating Go CIDR list: ${TEMP_GO}"
cat > "${TEMP_GO}" <<'GO_HEAD'
# Cloudflare CIDR list for Go IP extractor
# Auto-generated by update-cloudflare-ip.sh
# Last updated: {{DATE}}

GO_HEAD
sed -i "s/{{DATE}}/$(date -u '+%Y-%m-%d %H:%M:%S UTC')/" "${TEMP_GO}"
echo "$ALL_CIDRS" >> "${TEMP_GO}"

log_info "Validating Nginx config..."
if command -v nginx &>/dev/null; then
	if nginx -t -c /etc/nginx/nginx.conf 2>/dev/null; then
		log_info "Nginx config valid"
	else
		log_error "Nginx config invalid, rolling back"
		exit 1
	fi
else
	log_info "Nginx not installed, skipping validation"
fi

log_info "Validating Caddy config..."
if command -v caddy &>/dev/null; then
	if caddy validate --config /etc/caddy/Caddyfile 2>/dev/null; then
		log_info "Caddy config valid"
	else
		log_error "Caddy config invalid, rolling back"
		exit 1
	fi
else
	log_info "Caddy not installed, skipping validation"
fi

log_info "Checking for changes..."
CHANGED=false
for pair in "${NGINX_OUT}:${TEMP_NGINX}" "${CADDY_OUT}:${TEMP_CADDY}" "${GO_OUT}:${TEMP_GO}"; do
	DST="${pair%%:*}"
	SRC="${pair##*:}"
	if [ ! -f "$DST" ] || ! cmp -s "$SRC" "$DST"; then
		CHANGED=true
		break
	fi
done

if [ "$CHANGED" = false ]; then
	log_info "No changes detected, skipping reload"
	cleanup
	exit 0
fi

log_info "Atomically replacing config files..."
cp "${TEMP_NGINX}" "${NGINX_OUT}"
cp "${TEMP_CADDY}" "${CADDY_OUT}"
cp "${TEMP_GO}" "${GO_OUT}"

log_info "Reloading services..."
if systemctl is-active --quiet nginx 2>/dev/null; then
	systemctl reload nginx
	log_info "Nginx reloaded"
fi

if systemctl is-active --quiet caddy 2>/dev/null; then
	caddy reload --config /etc/caddy/Caddyfile 2>/dev/null || true
	log_info "Caddy reloaded"
fi

if systemctl is-active --quiet ip-lookup 2>/dev/null; then
	log_info "Go backend will pick up changes via fsnotify (no restart needed)"
fi

log_info "Cloudflare CIDR sync completed successfully"
